events {}

http {

    proxy_cache_path /tmp/cache levels=1:2 keys_zone=STATIC:10m inactive=60m;

    server {
        listen 80;

        location /reports/ {

            proxy_pass http://minio:9000/reports/;

            proxy_cache STATIC;
            proxy_cache_valid 200 30m;

            add_header X-Cache-Status $upstream_cache_status;
        }
    }
}